[project]
name = "openwebui_service"
version = "1.0.0"
description = "Open WebUI Service"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "open-webui>=0.8.3",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
]
