[project]
name = "openwebui_service"
version = "1.0.0"
description = "Open WebUI Service"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "open-webui",
    "psycopg2-binary",
    "python-dotenv",
]
